#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Allison Fitzgerald's Blog
permalink: /blog/:title/

# folio theme below
markdown: kramdown
twitter_username: allisonleef
email: afitzgerald5555@gmail.com
highlighter: rouge

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/